version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio_local
    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  api:
    build: .
    container_name: node_api
    ports:
      - "3000:3000"
    environment:
      - MINIO_HOST=minio             # O Docker resolve isso para o IP do container minio
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio

volumes:
  minio_data: